// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCi7ebMe27bYC5va840cB3h2NFYKHqLiN4',
      appId: '1:449686849785:web:eeb007d0ebde7101b2fa28',
      messagingSenderId: '449686849785',
      projectId: 'tabletap-45899',
      authDomain: 'tabletap-45899.firebaseapp.com',
      storageBucket: 'tabletap-45899.appspot.com',
      databaseURL: "https://tabletap-45899-default-rtdb.firebaseio.com/");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCElBE4fNbjUCilQ7zyurFycEzj2tlBHg',
    appId: '1:449686849785:android:2a878bdd533682a6b2fa28',
    messagingSenderId: '449686849785',
    projectId: 'tabletap-45899',
    storageBucket: 'tabletap-45899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjM1okWNEM9Ahec7U0PEj8pM5-6ye-uA',
    appId: '1:449686849785:ios:b0d8059cf5479c17b2fa28',
    messagingSenderId: '449686849785',
    projectId: 'tabletap-45899',
    storageBucket: 'tabletap-45899.appspot.com',
    iosBundleId: 'com.example.tableTapCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjM1okWNEM9Ahec7U0PEj8pM5-6ye-uA',
    appId: '1:449686849785:ios:25455f12284a1a26b2fa28',
    messagingSenderId: '449686849785',
    projectId: 'tabletap-45899',
    storageBucket: 'tabletap-45899.appspot.com',
    iosBundleId: 'com.example.tableTapCustomer.RunnerTests',
  );
}
