name: table_tap_admin
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  dio: ^5.4.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4

  flutter:
    sdk: flutter
    
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  log_print: ^0.0.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
